### ISSUE TITLE
Add input validation

### ISSUE THREAD

**Issue by D3n0Duz** [D3n0Duz/go-docker-tutorial#10]
Validate each type of input with regex that allows certain characters only.
This should be done in the front end and also in the backend in order to be secure and safe.
https://www.owasp.org/index.php/OWASP_Validation_Regex_Repository

**Comment by sulf4t** [comment]
issue is implemented in the regex pull request

**Comment by dduzgun** [comment]
https://github.com/D3n0Duz/go-docker-tutorial/pull/17
