### ISSUE TITLE
Add rate limiting to make calls

### ISSUE THREAD

**Issue by D3n0Duz** [D3n0Duz/go-docker-tutorial#11]
Limit the number of call from a certain user (looking for the IP that does the call) to 5 requests per hours. If the user has 5 requests per hour, add a captcha validation (invisible captcha).
https://developers.google.com/recaptcha/docs/invisible

**Comment by dduzgun** [comment]
This needs to be done in the infrastructure side within our API Gateway. Should be assigned to the infrastructure repository.
